name: Python Tests

on: 
  workflow_dispatch:
  push:
    branches:
      - main
      - develop

  pull_request:
    branches:
      - main

jobs:
  ci:
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install dependencies
        run: |
          python3 -m pip install --upgrade pip

          python3 -m pip install -r requirements.txt
      - name: Run tests and Upload coverage reports to Codecov
        run: |
          python3 -m pip install pytest
          pytest tests --cov
          curl -Os https://uploader.codecov.io/latest/linux/codecov
          chmod +x codecov
          ./codecov -t ${{secrets.CODECOV_TOKEN}}

